// flow-typed signature: ea13f6e53ef042b685112b82bd7a8bc0
// flow-typed version: <<STUB>>/cytoscape-dagre_v^2.2.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cytoscape-dagre'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cytoscape-dagre' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cytoscape-dagre/cytoscape-dagre' {
  declare module.exports: any;
}

declare module 'cytoscape-dagre/src/assign' {
  declare module.exports: any;
}

declare module 'cytoscape-dagre/src/defaults' {
  declare module.exports: any;
}

declare module 'cytoscape-dagre/src/index' {
  declare module.exports: any;
}

declare module 'cytoscape-dagre/src/layout' {
  declare module.exports: any;
}

declare module 'cytoscape-dagre/test/example' {
  declare module.exports: any;
}

declare module 'cytoscape-dagre/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cytoscape-dagre/cytoscape-dagre.js' {
  declare module.exports: $Exports<'cytoscape-dagre/cytoscape-dagre'>;
}
declare module 'cytoscape-dagre/src/assign.js' {
  declare module.exports: $Exports<'cytoscape-dagre/src/assign'>;
}
declare module 'cytoscape-dagre/src/defaults.js' {
  declare module.exports: $Exports<'cytoscape-dagre/src/defaults'>;
}
declare module 'cytoscape-dagre/src/index.js' {
  declare module.exports: $Exports<'cytoscape-dagre/src/index'>;
}
declare module 'cytoscape-dagre/src/layout.js' {
  declare module.exports: $Exports<'cytoscape-dagre/src/layout'>;
}
declare module 'cytoscape-dagre/test/example.js' {
  declare module.exports: $Exports<'cytoscape-dagre/test/example'>;
}
declare module 'cytoscape-dagre/webpack.config.js' {
  declare module.exports: $Exports<'cytoscape-dagre/webpack.config'>;
}
