// flow-typed signature: 18b021a81cb79780946c322eb57106f6
// flow-typed version: <<STUB>>/react-graph-vis_v^1.0.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-graph-vis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-graph-vis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-graph-vis/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-graph-vis/lib/index.js' {
  declare module.exports: $Exports<'react-graph-vis/lib/index'>;
}
