// flow-typed signature: d46f3c1f67b62986b449fa787c493aeb
// flow-typed version: <<STUB>>/react-cytoscape_v^1.0.6/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cytoscape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cytoscape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cytoscape/build/components/ReactCytoscape' {
  declare module.exports: any;
}

declare module 'react-cytoscape/build/index' {
  declare module.exports: any;
}

declare module 'react-cytoscape/sample/app/Graph' {
  declare module.exports: any;
}

declare module 'react-cytoscape/sample/app/index' {
  declare module.exports: any;
}

declare module 'react-cytoscape/sample/public/bundle' {
  declare module.exports: any;
}

declare module 'react-cytoscape/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cytoscape/build/components/ReactCytoscape.js' {
  declare module.exports: $Exports<'react-cytoscape/build/components/ReactCytoscape'>;
}
declare module 'react-cytoscape/build/index.js' {
  declare module.exports: $Exports<'react-cytoscape/build/index'>;
}
declare module 'react-cytoscape/sample/app/Graph.js' {
  declare module.exports: $Exports<'react-cytoscape/sample/app/Graph'>;
}
declare module 'react-cytoscape/sample/app/index.js' {
  declare module.exports: $Exports<'react-cytoscape/sample/app/index'>;
}
declare module 'react-cytoscape/sample/public/bundle.js' {
  declare module.exports: $Exports<'react-cytoscape/sample/public/bundle'>;
}
declare module 'react-cytoscape/webpack.config.js' {
  declare module.exports: $Exports<'react-cytoscape/webpack.config'>;
}
